### ISSUE TITLE
KeyError: 'choices' in chat.py

### ISSUE THREAD

**Issue by Konfekt** [madox2/vim-ai#102]
Just left here for reference, as it rarely occurred

```vim
Trovato errore eseguendo function vim_ai#AIChatRun[32]..function vim_ai#AIChatRun:
riga   26:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/epn/.config/.vim/plugged/vim-ai/py/chat.py", line 91, in <module>
    handle_completion_error(error)
  File "/home/epn/.config/.vim/plugged/vim-ai/py/utils.py", line 259, in handle_completion_error
    raise error
  File "/home/epn/.config/.vim/plugged/vim-ai/py/chat.py", line 85, in <module>
    render_text_chunks(text_chunks, is_selection)
  File "/home/epn/.config/.vim/plugged/vim-ai/py/utils.py", line 93, in render_text_chunks
    for text in chunks:
  File "/home/epn/.config/.vim/plugged/vim-ai/py/chat.py", line 83, in map_chunk
    return resp['choices'][0]['delta'].get('content', '')
KeyError: 'choices'
```

**Comment by madox2** [comment]
Fixed in #139
