### ISSUE TITLE
GPT-4 doesn't work

### ISSUE THREAD

**Issue by jpchauvel** [madox2/vim-ai#23]
I've tried setting the following options:

In my `.vimrc`:

```vim script
let g:vim_ai_chat = {
\  "options": {
\    "model": "gpt-4",
\    "temperature": 0.2,
\  },
\}
```

And on the fly:

```vim script
let g:vim_ai_chat['options']['model'] = 'gpt-4'
let g:vim_ai_chat['options']['temperature'] = 0.2
```

All I get is this error message:

```Python
Error detected while processing function vim_ai#AIChatRun:
line   30:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hellhound/.vim/plugged/vim-ai/py/chat.py", line 82, in <module>
    handle_completion_error(error)
  File "/Users/hellhound/.vim/plugged/vim-ai/py/utils.py", line 149, in handle_completion_error
    raise error
  File "/Users/hellhound/.vim/plugged/vim-ai/py/chat.py", line 77, in <module>
    render_text_chunks(text_chunks)
  File "/Users/hellhound/.vim/plugged/vim-ai/py/utils.py", line 41, in render_text_chunks
    for text in chunks:
  File "/Users/hellhound/.vim/plugged/vim-ai/py/utils.py", line 123, in openai_request
    with urllib.request.urlopen(req, timeout=request_timeout) as response:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Press ENTER or type command to continue
```

My system specs:
![Screenshot 2023-04-24 at 18 21 47](https://user-images.githubusercontent.com/13751988/234136233-f46fe1d8-d89d-4dbe-8160-45cab4091527.png)

I'm using MacPorts 2.8.1 and I have the following Python's version installed:
```  
python39 @3.9.16_0+lto+optimizations (active)
```

**Comment by madox2** [comment]
Hi, gpt-4 is not yet available for everybody, but you can to [join API waitlist](https://openai.com/waitlist/gpt-4-api)
