### ISSUE TITLE
Every command returning 429 Http Status

### ISSUE THREAD

**Issue by sheldonth** [madox2/vim-ai#24]
Hi, 

Everything seems to be working with my install but no matter what command I run I see 429
```
Error invoking 'python_execute_file' on channel 5 (python3-script-host):
Traceback (most recent call last):
  File "/Users/s/.vim/plugged/vim-ai/py/complete.py", line 54, in <module>
    handle_completion_error(error)
  File "/Users/s/.vim/plugged/vim-ai/py/utils.py", line 149, in handle_completion_error
    raise error
  File "/Users/s/.vim/plugged/vim-ai/py/complete.py", line 52, in <module>
    render_text_chunks(text_chunks)
  File "/Users/s/.vim/plugged/vim-ai/py/utils.py", line 41, in render_text_chunks
    for text in chunks:
  File "/Users/s/.vim/plugged/vim-ai/py/utils.py", line 123, in openai_request
    with urllib.request.urlopen(req, timeout=request_timeout) as response:
 
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216,
 in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525,
 in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634,
 in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563,
 in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496,
 in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643,
 in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```
Any idea why that might be happening? I have plenty of credits and a paid account with OpenAI

**Comment by madox2** [comment]
Hi, it still looks like a usage limit problem: https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests 

Are you sure you are on "Pay as you go" plan? (you can find out on Manage Account -> Billing -> Overview)

Please also verify the limits in your OpenAI account - Manage Account -> Billing -> Usage limits
