### ISSUE TITLE
TimeoutError when when using AIChat

### ISSUE THREAD

**Issue by MartinDelille** [madox2/vim-ai#49]
I'm using AIChat with the following buffer:

```
>>> user

I have this error 

C:\Users\LyloDevW10\scoop\apps\pyenv\current\pyenv-win\libexec\pyenv.vbs(0, 1) Microsoft VBScript runtime error: File not found


<<< assistant
```

It leads to the following error:

```
Error detected while processing function vim_ai#AIChatRun[30]..provider#python3#Call:
line   18:
Error invoking 'python_execute_file' on channel 8 (python3-script-host):
Traceback (most recent call last):
  File "/Users/martin/.local/share/nvim/plugged/vim-ai/py/chat.py", line 83, in <module>
    handle_completion_error(error)
  File "/Users/martin/.local/share/nvim/plugged/vim-ai/py/utils.py", line 172, in handle_completion_err
or
    raise error
  File "/Users/martin/.local/share/nvim/plugged/vim-ai/py/chat.py", line 77, in <module>
    render_text_chunks(text_chunks)
  File "/Users/martin/.local/share/nvim/plugged/vim-ai/py/utils.py", line 53, in render_text_chunks
    for text in chunks:
  File "/Users/martin/.local/share/nvim/plugged/vim-ai/py/utils.py", line 136, in openai_request
    with urllib.request.urlopen(req, timeout=request_timeout) as response:
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 496, in _call_chai
n
    result = func(*args)
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 1391, in https_ope
n
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/martin/.pyenv/versions/3.10.6/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
Press ENTER or type command to continue
```

Despite the buffer content, I must precise that I'm working on neovim on MacOS.

**Comment by madox2** [comment]
Is this error happening also in the latest plugin version?

**Comment by madox2** [comment]
Closing due to inactivity
