### ISSUE TITLE
fail gracefully on missing connection

### ISSUE THREAD

**Issue by Konfekt** [madox2/vim-ai#63]
At the moment, in case of a connection problem, `:AIChat` produces

```vim
Trovato errore eseguendo function vim_ai#AIChatRun:
riga   30:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1291, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1337, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1286, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1444, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 956, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Errore temporaneo nella risoluzione del nome

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/epn/.config/.vim/plugged/vim-ai/py/chat.py", line 84, in <module>
    handle_completion_error(error)
  File "/home/epn/.config/.vim/plugged/vim-ai/py/utils.py", line 195, in handle_completion_error
    raise error
  File "/home/epn/.config/.vim/plugged/vim-ai/py/chat.py", line 78, in <module>
    render_text_chunks(text_chunks)
  File "/home/epn/.config/.vim/plugged/vim-ai/py/utils.py", line 68, in render_text_chunks
    for text in chunks:
  File "/home/epn/.config/.vim/plugged/vim-ai/py/utils.py", line 157, in openai_request
    with urllib.request.urlopen(req, timeout=request_timeout) as response:
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Errore temporaneo nella risoluzione del nome>
Answering...
```

Would not a one-line hint at a missing internet connection be sufficient?
For this, maybe a simple `abort` following the function name

```vim
" autoload/vim_ai.vim (line 144)
function! vim_ai#AIChatRun(is_selection, config, ...) range
```

 could suffice?

**Comment by madox2** [comment]
Error handling has been improved, now it should only display error reason: `urlopen error [Errno -3] Errore temporaneo nella risoluzione del nome`
